language: objective-c
osx_image: xcode8.1
before_install:
    - rvm use system
    - sudo gem install cocoapods -v '1.1.1'
    - cd ./Example
    - pod install
script:
    xcodebuild -workspace SwiftyVerticalScrollBar.xcworkspace -scheme SwiftyVerticalScrollBar-Example -sdk iphonesimulator
