language: objective-c
osx_image: xcode7.3
before_install:
    - rvm use system
    - sudo gem install cocoapods -v '0.39.0'
    - cd ./Example
    - pod install
script:
    xcodebuild -workspace SwiftyVerticalScrollBar.xcworkspace -scheme SwiftyVerticalScrollBar-Example -sdk iphonesimulator
